config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :schools
  resources :members
  root 'schools#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord

  has_and_belongs_to_many :schools

  validates :name, presence: true, uniqueness: true
  validates :email, format: { with: /(\A([a-z]*\s*)*\<*([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\>*\Z)/i }
end

app/models/school.rb
class School < ApplicationRecord

  has_and_belongs_to_many :members

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.all
  end

  def new
    @member = Member.new
    @schools = School.all
  end

  def create
    @member = Member.create(member_params)
    if @member.save
      redirect_to member_path(@member)
    else
      render 'new'
    end
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
    @schools = School.all
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to member_path(@member)
    else
      render 'edit'
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    flash[:notice] = 'Member deleted successfully'
    redirect_to members_path
  end

  private
  def member_params
    params.require(:member).permit(:name, :email, :school_ids => [])
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    @schools = School.all
  end

  def new
    @school = School.new
  end

  def create
    @school = School.create(school_params)
    if @school.save
      redirect_to school_path(@school.id)
    else
      render 'new'
    end
  end

  def show
    @school = School.find(params[:id])
  end

  def edit
    @school = School.find(params[:id])
  end

  def update
    @school = School.find(params[:id])
    @school.update(school_params)
    redirect_to school_path(@school.id)
  end

  def destroy
    @school = School.find(params[:id])
    @school.destroy
    flash[:notice] = 'School deleted successfully'
    redirect_to schools_path
  end

  private
  def school_params
    params.require(:school).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h3><%= link_to 'Schools', schools_path %> | <%= link_to 'Members', members_path %></h3>
    <br />
    <%= notice %>
    <br />
    <%= yield %>
  </body>
</html>

app/views/members/edit.html.erb
<% if @member.errors.any? %>
  <section id="errors" >
    <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

<%= form_for @member do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit %>
  <br />
  <br />
  Select member's schools:
  <% if @schools %>
    <%= f.collection_check_boxes(:school_ids, @schools, :id, :name) do |b| %>
      <%= b.label(class: "check-box") do %>
        <%= b.check_box %>
        <%= b.object.name %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/members/index.html.erb
<a class="add-link" href='/members/new'>Add a member</a>
<h1>Members listed:</h1>

<% if @members.all.any? %>
  <% @members.all.order(:name).each do |member| %>
    <h2><%= link_to member.name, member_path(member) %></h2>
  <% end %>
<% else %>
  <h1>No members yet</h1>
<% end %>

app/views/members/new.html.erb
<% if @member.errors.any? %>
  <section id="errors" >
    <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

<%= form_for @member do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit %>
  <br />
  <br />
  Select member's schools:
  <% if @schools %>
    <%= f.collection_check_boxes(:school_ids, @schools, :id, :name) do |b| %>
      <%= b.label(class: "check-box") do %>
        <%= b.check_box %>
        <%= b.object.name %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/members/show.html.erb
<%= link_to "Edit", edit_member_path(@member), class: "edit-link" %> <%= link_to "Delete", member_path(@member), class: "delete-link", method: :delete %>
<h1><%= @member.name %></h1>
<p>Email: <%= @member.email %></p>

<div class="box-list">
  <h3>Schools</h3>
    <ul>
      <% @member.schools.order(:name).each do |school| %>
        <li><%= school.name %></li>
      <% end %>
    </ul>
</div>

app/views/schools/edit.html.erb
<% if @school.errors.any? %>
  <section id="errors" >
    <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

<%= form_for @school do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/schools/index.html.erb
<a class="add-link" href='/schools/new'>Add a school</a>
<h1>Schools listed:</h1>

<% if @schools.all.any? %>
  <% @schools.all.order(:name).each do |school| %>
    <h2><%= link_to school.name, school_path(school) %></h2>
  <% end %>
<% else %>
  <h1>No schools yet</h1>
<% end %>

app/views/schools/new.html.erb
<% if @school.errors.any? %>
  <section id="errors" >
    <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

<%= form_for @school do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/schools/show.html.erb
<%= link_to "Edit", edit_school_path(@school), class: "edit-link" %> <%= link_to "Delete", school_path(@school), class: "delete-link", method: :delete %>
<h1><%= @school.name %></h1>

<div class="box-list">
  <h3>Members</h3>
    <ul>
      <% @school.members.order(:name).each do |member| %>
        <li><%= link_to member.name, member_path(member) %></li>
      <% end %>
    </ul>
</div>